apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-scheduler
  namespace: trustle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-scheduler
  template:
    metadata:
      labels:
        app: task-scheduler
    spec:
      containers:
        - name: api
          image: task-scheduler:minikube
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres.trustle.svc.cluster.local:5432/trustle
            - name: SCHEDULER_ENABLE
              value: "true"
            - name: API_KEY
              value: "changeme"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: task-scheduler
  namespace: trustle
spec:
  type: NodePort
  selector:
    app: task-scheduler
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
